package com.openclaw.harness.model;

import com.openclaw.harness.generation.FileChange;
import com.openclaw.harness.generation.PatchPlan;
import com.openclaw.harness.gates.RiskLevel;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class StubCodeModelProvider implements CodeModelProvider {

    @Override
    public String providerKey() {
        return "stub";
    }

    @Override
    public CodeModelResponse generatePatch(CodeModelRequest request) {
        String taskId = request.context().taskItems().isEmpty() ? request.objective() : request.context().taskItems().getFirst();
        PatchPlan plan = new PatchPlan(
                "patch-" + Math.abs(request.objective().hashCode()),
                taskId,
                "stub provider 生成的 Skill Store 受控补丁计划",
                List.of(
                        new FileChange("skill-store/README.md", "modify", "\n## Harness 生成记录\n\n- " + request.objective() + "\n", taskId, "记录代码生成演示"),
                        new FileChange("skill-store/backend/src/test/java/com/openclaw/skillstore/generated/GeneratedPatchTest.java", "create", "package com.openclaw.skillstore.generated;\n\nclass GeneratedPatchTest {\n}\n", taskId, "生成后端测试候选"),
                        new FileChange("skill-store/frontend/src/generated/harness-generated-note.ts", "create", "export const harnessGeneratedNote = 'generated by harness stub provider';\n", taskId, "生成前端候选文件")
                ),
                RiskLevel.MEDIUM,
                List.of("spec.md", "plan.md", "tasks.md", "contracts/")
        );
        return new CodeModelResponse(true, plan, List.of());
    }
}
